# Site settings
title: 个人主页
description: 这是一个IT人的主页
keywords: IT,网络安全,生活,旅行
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://minshenwang.github.io" # the base hostname & protocol for 
#language: zh-CN
#timezone: UTC
# your site

# Paginate（分页）
#gems: [jekyll-paginate]

# 分页时每页博文数量
#paginate: 10
#paginate_path: "page:num"


# Build settings
# 语法高亮
#highlighter: pygments
# markdown解释器
#markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

#relative_permalinks: true
#博文的链接样式
permalink: /:year-:month-:day-:title.html

favicon: /assets/image/favicon.ico

# 博客作者相关
author:
  name: Minshen Wang
  email: anikewang@qq.com
  link: https://minshenwang.github.io
 # weibo: http://www.weibo.com
 # weibo_username: trace-night
  github: https://github.com/minshenwang
  github_username: minshenwang

#categories:
  



locals:
  tags: 标签
  about: 关于
  active: 技术

# categories: 

subscribe_rss: /404.html

# 头像
avatar: /assets/image/avatar.png


# 网站CSS路径
css: /assets/css/


# 网站JS路径
js: /assets/js/


# 网站图片路径
image: /assets/image/
 


# disqus 设置
#disqus:
  #shortname: minshen
